#!/usr/bin/env bash
# DB 版 top 100 — 使用歷史宇宙快照，無存活者偏差
.venv/bin/python backtest.py --show-skipped \
  --start               2009-01-01 \
  --capital             1000000 \
  --strategies          ema_trend \
  --stop-loss           8 \
  --trail-stop          0.15 \
  --trail-stop-bull     0.22 \
  --trail-stop-rs-bonus 0.05 \
  --trail-activation    0.02 \
  --max-positions       10 \
  --position-pct        0.20 \
  --stocks              80 \
  --max-price           2000 \
  --min-rs              0.05 \
  --market-filter \
  --early-exit-days     0 \
  --market-ma           20 \
  --time-stop-days      20 \
  --time-stop-min-pct   0.05 \
  --breadth-filter \
  --breadth-min         0.50 \
  --slippage            0.002 \
  --max-vol-pct         0.03 \
  --min-atr-pct         3.0 \
  --min-ema-dev         0.03 \
  --dev-low-thr         0.03 \
  --dev-high-thr        0.05 \
  --dev-low-pct         0.15 \
  --dev-high-mult       1.4 \
  --market-max-20d-gain 0.10 \
  --market-max-10d-gain 0.07 \
  --market-atr-max      0.015 \
  --pyramid-gain        0.20 \
  --pyramid-gain2       0.40 \
  --pyramid-rs-min      0.05 \
  --pyramid-alloc       0.50 \
  --market-bull-entry
