#!/usr/bin/env bash
# DB 版 top 100 — 使用歷史宇宙快照，無存活者偏差（stocks.db）
.venv/bin/python backtest.py --show-skipped \
  --db-backend          duckdb \
  --db-path             data/stocks.db \
  --start               2009-01-01 \
  --capital             1000000 \
  --strategies          ema_trend \
  --stop-loss           8 \
  --trail-stop          0.15 \
  --trail-stop-bull     0.18 \
  --trail-stop-rs-bonus 0.08 \
  --trail-activation    0.02 \
  --max-positions       4 \
  --position-pct        0.25 \
  --stocks              80 \
  --max-price           2000 \
  --min-rs              0.13 \
  --max-rs              0.40 \
  --rank-mode           hybrid \
  --rank-w-conf         0.00 \
  --rank-w-rs           0.41 \
  --rank-w-dev          0.20 \
  --rank-w-rs-sweet     0.19 \
  --rank-rs-center      0.12 \
  --rank-rs-span        0.25 \
  --rank-rs-sweet-spot  0.20 \
  --rank-rs-sweet-tolerance 0.10 \
  --rank-dev-sweet-spot 0.05 \
  --rank-dev-tolerance  0.03 \
  --rank-breadth-sweet-spot 0.60 \
  --rank-breadth-tolerance 0.12 \
  --market-filter \
  --early-exit-days     0 \
  --market-ma           20 \
  --time-stop-days      20 \
  --time-stop-min-pct   0.05 \
  --breadth-filter \
  --breadth-min         0.50 \
  --breadth-max         1.00 \
  --slippage            0.002 \
  --max-vol-pct         0.03 \
  --min-atr-pct         3.0 \
  --min-ema-dev         0.04 \
  --dev-low-thr         0.03 \
  --dev-high-thr        0.05 \
  --dev-low-pct         0.10 \
  --dev-high-mult       1.6 \
  --market-max-20d-gain 0.10 \
  --market-max-10d-gain 0.07 \
  --market-atr-max      0.015 \
  --pyramid-gain        0.15 \
  --pyramid-gain2       0.35 \
  --pyramid-rs-min      0.05 \
  --pyramid-alloc       0.60 \
  --market-bull-entry  \
  --market-dd-threshold    0.10 \
  --market-dd-max-positions 2 \
  --rs-pos-high-thr     0.15 \
  --rs-pos-high-mult    2.00 \
  --rs-pos-low-thr      0.07 \
  --rs-pos-low-mult     0.80 \
  --short-util-max      0.08 \
  --rank-w-chip         0.25 \
  --rank-w-vol-surge    0.00 \
  --rank-vol-surge-sweet-spot 0.75 \
  --rank-vol-surge-tolerance  0.50 \
  --vix-park-hi         30 \
  --vix-park-lo         20 \
  --stop-atr-mult           2.5 \
  --min-rank-score          0.38 \
  "$@"